### Get All Categories
GET http://localhost:5000/api/categories

### GET Category By Id
GET http://localhost:5000/api/categories/02f20603-df22-4881-af40-44bf02b8f677

### Create One Category
POST http://localhost:5000/api/categories
Access-Token: 

{
  "name":"PHP"
}

### Update Category By Id
PUT http://localhost:5000/api/categories/2ddfd633-283b-4d52-8d5a-c1ab4bcf41d7
Access-Token:

{
  "name":"Code Igniter"
}

### Deleted Category By Id
DELETE http://localhost:5000/api/categories/2ddfd633-283b-4d52-8d5a-c1ab4bcf41d7
Access-Token:


### Register User
POST  http://localhost:5000/api/users/register

{
  "username":"rizqy",
  "email":"rizqy@gmail.com",
  "password":"123",
  "role":""
}

### Login User
POST http://localhost:5000/api/users/login

{
  "email":"ihksan@gmail.com",
  "password":"123"
}

### Get Token if user already loggedin
GET http://localhost:5000/api/users/token

### Logout User
DELETE http://localhost:5000/api/users/logout

### GET ALL USERS
GET http://localhost:5000/api/users

### GET USER BY ID
GET http://localhost:5000/api/users/4b44a979-9257-4c0d-90df-476150cff7d3