### Get All Categories
GET http://localhost:5000/api/categories

### GET Category By Id
GET http://localhost:5000/api/categories/03970acc-86de-4171-902a-ea4b5c014286

### Create One Category
POST http://localhost:5000/api/categories
Access-Token: 

{
  "name":"Golang"
}

### Update Category By Id
PUT http://localhost:5000/api/categories/2ddfd633-283b-4d52-8d5a-c1ab4bcf41d7
Access-Token:

{
  "name":"Code Igniter"
}

### Deleted Category By Id
DELETE http://localhost:5000/api/categories/2ddfd633-283b-4d52-8d5a-c1ab4bcf41d7
Access-Token:


### Register User
POST  http://localhost:5000/api/users/register

{
  "username":"sandy",
  "email":"sandy@gmail.com",
  "password":"123",
  "role":"admin"
}

### Login User
POST http://localhost:5000/api/users/login

{
  "email":"azhi@gmail.com",
  "password":"123"
}

### Get Token if user already loggedin
GET http://localhost:5000/api/users/token

### Logout User
DELETE http://localhost:5000/api/users/logout

### GET ALL USERS
GET http://localhost:5000/api/users

### GET USER BY ID
GET http://localhost:5000/api/users/cf0d06e7-7168-4e50-be5a-9ec10a52cac9



### CREATE CLASS
POST http://localhost:5000/api/classes
Access-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNmMGQwNmU3LTcxNjgtNGU1MC1iZTVhLTllYzEwYTUyY2FjOSIsImV4cCI6MTY5MzQ1ODUwMn0.xh-P7YTglovrZ8801QnX83V2r-j6NbtQoIaxQ0T7qj0

{
  "name":"Kelas Dasar Javascript",
  "created_by":"cf0d06e7-7168-4e50-be5a-9ec10a52cac9",
  "category_id":"03970acc-86de-4171-902a-ea4b5c014286",
  "description":"Javascript is Easy Peasey The Lemon Squezy",
  "thumbnail":"",
  "trailer":""
}

### Get All Classes
GET http://localhost:5000/api/classes

### Get Class By Id
GET http://localhost:5000/api/classes/892a76f0-1380-4905-9db7-a9d53d6bc3af